### ISSUE TITLE
Pomylka w stylach

### ISSUE THREAD

**Issue by teitbite** [GavickPro/GK-News-Show-Pro#39]
Kiedy wybieramy w Module mode "Centered Title Overlay" to otwiera sie panel dla "Product Gallery - Portal Mode Settings" a nie to co chcielismy.

https://www.gavick.com/forums/255/center-title-overlay-not-showing-setting-43574?p=218665#p218665

**Comment by piotrkunicki** [comment]
To jest repo News Show Pro dla WP..

**Comment by teitbite** [comment]
Nie mamy innego repo dla NSP, przynajmniej ja nie jestem dodany. Prosze przenies to gdzie trzeba, bo userzy nie moga uzywac "Centered Title Overlay" stylu przez ten bug.

**Comment by piotrkunicki** [comment]
Tutaj jest repo dla J!:
https://github.com/GavickPro/News-Show-Pro-GK5/
no i jest publiczne..
