### ISSUE TITLE
Title shows html special characters instead of  quotes

### ISSUE THREAD

**Issue by alco321** [GavickPro/GK-News-Show-Pro#40]
Hello. 
I am facing a simple (I hope) problem with the titles that the module is showing. I am using standart mode and as data source I use RSS feed.
Sometimes , when a title has some  quotes the module  shows the html code instead of "
For an example here is the title from the source (greek lang)
"OXI" των κατοίκων Ελατίων στα απορρίμματα
And here is what module shows
& quot ; OXI & quot ; των κατοίκων Ελατίων στα απορρίμματα
(I have inserted some spaces in the example)
How can I solve this?
Thank you

**Comment by dziudek** [comment]
Hello,

First of all - do you mean News Show Pro GK5 for Joomla! or GK News Show Pro for WordPress?

**Comment by alco321** [comment]
You are absolutelly right. I forgot...
I 'm talking about joomla

**Comment by dziudek** [comment]
Your issue is probably caused by this line: https://github.com/GavickPro/News-Show-Pro-GK5/blob/master/mod_news_pro_gk5/tmpl/view.php#L26

Please try to change it to:

```php
$output = htmlspecialchars_decode(NSP_GK5_Utils::cutText(htmlspecialchars($item['title']), $config, 'title_limit', '&hellip;'));
```

**Comment by alco321** [comment]
Bingo!
Thank you so much!
